# Generated by Django 2.2.3 on 2019-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Електронна пошта')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('date_birth', models.DateField(verbose_name='Дата народження')),
                ('post', models.CharField(max_length=100, verbose_name='Посада')),
                ('image', models.ImageField(blank=True, upload_to='users', verbose_name='Зображення')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
