# Generated by Django 2.2.3 on 2019-07-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Текст')),
                ('description', models.TextField(blank=True, verbose_name='Текст')),
                ('url', models.URLField(verbose_name='URL адреса')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Тема')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('date_from', models.DateTimeField(verbose_name='Дата початку')),
                ('date_to', models.DateTimeField(verbose_name='Дата закінчення')),
                ('type', models.IntegerField(choices=[(1, 'Фіча'), (2, 'Баг')], verbose_name='Тип')),
                ('priority', models.IntegerField(choices=[(1, 'нормальний'), (2, 'високій'), (3, 'срочно')], verbose_name='Пріоритет')),
                ('estimated_time', models.PositiveIntegerField(verbose_name='Оціночний час в годинах')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_to_do', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TimeLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.PositiveIntegerField(verbose_name='Витрачений час в годинах')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Task')),
            ],
            options={
                'db_table': 'time_logging',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
