# Generated by Django 2.2.3 on 2019-07-08 09:04

from django.db import migrations, models
import tracker.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programers',
            field=models.ManyToManyField(to='user.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tracker.utils.models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
